doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
            eset:
                url: '%env(resolve:DATABASE_ESET_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    App\EsdPortal\Domain:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/EsdPortal/Domain/Entity'
                        prefix: 'App\EsdPortal\Domain\Entity'
                        alias: Main
            eset:
                connection: eset
                mappings:
                    App\Eset\Domain:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Eset/Domain/Entity'
                        prefix: 'App\Eset\Domain\Entity'
                        alias: Eset
